spring.data.mongodb.uri = mongodb+srv://dbhattacharyya2004_db_user:9dN5YDmJDTFN8C5a@cluster0.dqkj4xi.mongodb.net/?appName=Cluster0
spring.data.mongodb.database = journalDB
spring.data.mongodb.auto-index-creation = true
# the above is help to do auto indexing as spring boot not do it automatically , we have to tell it to do.