spring.data.mongodb.uri = 
spring.data.mongodb.database = journalDB
spring.data.mongodb.auto-index-creation = true
# the above is help to do auto indexing as spring boot not do it automatically , we have to tell it to do.